baseURL = 'http://psdatasets.org/'
languageCode = 'en-us'
title = 'PSdatasets.org'

[outputs]
  home = ["HTML", "RSS", "JSON"]
[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-bare-min-theme"
    disabled = false
